package fr.p10.mi.classe;
// Generated 12 mars 2014 16:13:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Intervenant generated by hbm2java
 */
public class Intervenant  implements java.io.Serializable {


     private long idi;
     private Statut statut;
     private String nom;
     private String prenom;
     private String mail;
     private String passwd;
     private String tel;
     private String enservice;
     private Set sessionses = new HashSet(0);
     private Set ecs = new HashSet(0);
     private Set agendas = new HashSet(0);

    public Intervenant() {
    }

	
    public Intervenant(long idi, Statut statut, String nom, String prenom, String mail, String passwd, String tel, String enservice) {
        this.idi = idi;
        this.statut = statut;
        this.nom = nom;
        this.prenom = prenom;
        this.mail = mail;
        this.passwd = passwd;
        this.tel = tel;
        this.enservice = enservice;
    }
    public Intervenant(long idi, Statut statut, String nom, String prenom, String mail, String passwd, String tel, String enservice, Set sessionses, Set ecs, Set agendas) {
       this.idi = idi;
       this.statut = statut;
       this.nom = nom;
       this.prenom = prenom;
       this.mail = mail;
       this.passwd = passwd;
       this.tel = tel;
       this.enservice = enservice;
       this.sessionses = sessionses;
       this.ecs = ecs;
       this.agendas = agendas;
    }
   
    public long getIdi() {
        return this.idi;
    }
    
    public void setIdi(long idi) {
        this.idi = idi;
    }
    public Statut getStatut() {
        return this.statut;
    }
    
    public void setStatut(Statut statut) {
        this.statut = statut;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getEnservice() {
        return this.enservice;
    }
    
    public void setEnservice(String enservice) {
        this.enservice = enservice;
    }
    public Set getSessionses() {
        return this.sessionses;
    }
    
    public void setSessionses(Set sessionses) {
        this.sessionses = sessionses;
    }
    public Set getEcs() {
        return this.ecs;
    }
    
    public void setEcs(Set ecs) {
        this.ecs = ecs;
    }
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }




}


