package fr.p10.mi.classe;
// Generated 12 mars 2014 16:13:29 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Statut generated by hbm2java
 */
public class Statut  implements java.io.Serializable {


     private long idstat;
     private String nom;
     private BigDecimal nbrh;
     private BigDecimal nbrhsup;
     private Set intervenants = new HashSet(0);

    public Statut() {
    }

	
    public Statut(long idstat, String nom, BigDecimal nbrh, BigDecimal nbrhsup) {
        this.idstat = idstat;
        this.nom = nom;
        this.nbrh = nbrh;
        this.nbrhsup = nbrhsup;
    }
    public Statut(long idstat, String nom, BigDecimal nbrh, BigDecimal nbrhsup, Set intervenants) {
       this.idstat = idstat;
       this.nom = nom;
       this.nbrh = nbrh;
       this.nbrhsup = nbrhsup;
       this.intervenants = intervenants;
    }
   
    public long getIdstat() {
        return this.idstat;
    }
    
    public void setIdstat(long idstat) {
        this.idstat = idstat;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public BigDecimal getNbrh() {
        return this.nbrh;
    }
    
    public void setNbrh(BigDecimal nbrh) {
        this.nbrh = nbrh;
    }
    public BigDecimal getNbrhsup() {
        return this.nbrhsup;
    }
    
    public void setNbrhsup(BigDecimal nbrhsup) {
        this.nbrhsup = nbrhsup;
    }
    public Set getIntervenants() {
        return this.intervenants;
    }
    
    public void setIntervenants(Set intervenants) {
        this.intervenants = intervenants;
    }




}


